### ISSUE TITLE
TypeError: 'NoneType' object is not iterable 请问这个问题怎么排除 我使用的是3090 pytorch1.8

### ISSUE THREAD

**Issue by YuanJZhang** [The-Learning-And-Vision-Atelier-LAVA/DASR#63]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/zyj/anaconda3/envs/action-rc-py36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/zyj/anaconda3/envs/action-rc-py36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zyj/anaconda3/envs/action-rc-py36/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    idx, data = r
TypeError: 'NoneType' object is not iterable

**Comment by yanjingke** [comment]
请问您解决了吗

**Comment by HanserEteRiRi** [comment]
请问解决了吗，我也遇到了这个问题
