### ISSUE TITLE
您好，我用自己的数据训练时出现这个错误，您可以帮我看一下吗？

### ISSUE THREAD

**Issue by gwp2021** [The-Learning-And-Vision-Atelier-LAVA/DASR#67]
### 非常感谢您的分享，但是我遇到一个问题，我的数据集是灰度图片，应该是矩阵维数错误，可是我没有找到读取图片的代码在哪里，应该如何修改代码？感谢！
`(DASR) # ./main.sh
./data_set/benchmark/Set14/HR
./data_set/benchmark/Set14/LR_bicubic
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]       Learning rate: 1.00e-3
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    t.train()
  File "/home/jovyan/sr/DASR-main/trainer.py", line 63, in train
    for batch, (hr, _, idx_scale) in enumerate(self.loader_train):
  File "/home/jovyan/sr/DASR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/jovyan/sr/DASR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/jovyan/sr/DASR-main/dataloader.py", line 38, in _ms_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jovyan/sr/DASR-main/dataloader.py", line 38, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jovyan/sr/DASR-main/data/multiscalesrdata.py", line 123, in __getitem__
    hr = self.get_patch(hr)
  File "/home/jovyan/sr/DASR-main/data/multiscalesrdata.py", line 164, in get_patch
    hr = common.augment(hr) if not self.args.no_augment else hr
  File "/home/jovyan/sr/DASR-main/data/common.py", line 44, in augment
    if hflip: img = img[:, ::-1, :]
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed`

**Comment by gwp2021** [comment]
已解决，手动将图片转换成RGB格式，可以正常train
